# Generated by Django 3.2.11 on 2023-05-04 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_studentsgroup_programs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsgroup',
            old_name='programs',
            new_name='courses',
        ),
    ]
