# Generated by Django 3.2.11 on 2023-05-04 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20230504_0727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='html',
        ),
        migrations.AddField(
            model_name='step',
            name='html',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step', to='users.htmlpage'),
        ),
        migrations.RemoveField(
            model_name='step',
            name='test',
        ),
        migrations.AddField(
            model_name='step',
            name='test',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step', to='users.test'),
        ),
    ]
