# Generated by Django 3.2.11 on 2023-04-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_program_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='image',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.ManyToManyField(blank=True, to='users.HtmlPage')),
                ('test', models.ManyToManyField(blank=True, to='users.Test')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='steps',
            field=models.ManyToManyField(blank=True, to='users.Step'),
        ),
    ]
