# Generated by Django 3.2.11 on 2023-05-04 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_course_coursetopic_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsgroup',
            name='programs',
            field=models.ManyToManyField(blank=True, to='users.Course'),
        ),
    ]
