# Generated by Django 3.2.11 on 2023-05-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20230504_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='order_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='order_number',
            field=models.IntegerField(default=0),
        ),
    ]
