# Generated by Django 3.2.11 on 2023-05-10 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20230510_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_right',
        ),
    ]
