# Generated by Django 3.2.11 on 2023-05-10 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_useranswer_answers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseTopic',
            new_name='Topic',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='course',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='users.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useranswer',
            name='topic',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='users.topic'),
            preserve_default=False,
        ),
    ]
