# Generated by Django 3.2.11 on 2023-05-10 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_useranswer_total_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='html',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='users.htmlpage'),
            preserve_default=False,
        ),
    ]
