# Generated by Django 3.2.11 on 2023-05-13 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20230510_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='name',
            new_name='title',
        ),
    ]
