# Generated by Django 3.2.11 on 2023-05-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20230513_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='avatar',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='date_birth',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='mail',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='responsible_1_fio',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='responsible_1_mail',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='responsible_1_phone',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='responsible_2_fio',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='responsible_2_mail',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='responsible_2_phone',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
