# Generated by Django 3.2.11 on 2023-05-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20230513_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='multiple',
            field=models.BooleanField(default=False),
        ),
    ]
