# Generated by Django 3.2.11 on 2023-05-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_question_multiple'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='order_number',
            field=models.IntegerField(default=None),
        ),
    ]
