# Generated by Django 3.2.11 on 2023-05-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_useranswer_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='time_spended',
            field=models.IntegerField(default=0),
        ),
    ]
