# Generated by Django 3.2.11 on 2023-05-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_useranswer_time_spended'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='order_number',
            field=models.IntegerField(default=0),
        ),
    ]
