# Generated by Django 3.2.11 on 2023-05-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_useranswer_total_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='end_date',
            field=models.DateField(default=None, verbose_name='deadline date'),
            preserve_default=False,
        ),
    ]
