# Generated by Django 3.2.11 on 2023-05-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_studentinfo_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
